name: test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Goのセットアップ
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: ./go.mod
          cache: true

      - name: 依存関係のダウンロード
        run: go mod download

      - name: テスト実行
        run: | # CI環境では環境変数"ENV=ci"を設定
          if [ -n "$ACT" ]; then
            go test -race ./...
          else
            env ENV=ci go test -race ./...
          fi
